# Generated by Django 2.1.5 on 2020-05-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_chart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='tagid',
            field=models.IntegerField(null=True),
        ),
    ]
