# Generated by Django 2.1.5 on 2020-05-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0005_auto_20200503_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='tagid',
            field=models.IntegerField(null=True),
        ),
    ]
