# Generated by Django 2.1.5 on 2020-09-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0006_auto_20200503_2338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chart',
            new_name='vend1',
        ),
    ]
