# Generated by Django 2.1.5 on 2020-09-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0007_auto_20200927_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vend1',
            options={'verbose_name_plural': 'vend1'},
        ),
    ]
