# Generated by Django 2.1.5 on 2020-09-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0008_auto_20200927_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='vend2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagid', models.IntegerField(null=True)),
                ('item', models.TextField(max_length=50)),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'vend2',
            },
        ),
    ]
