# Generated by Django 2.1.5 on 2020-09-28 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0010_sold1_sold2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold1',
            name='saleTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sold2',
            name='saleTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
