# Generated by Django 2.1.5 on 2020-10-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0011_auto_20200928_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'sold2',
            },
        ),
    ]
