# Generated by Django 2.1.5 on 2020-10-03 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0012_alert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name_plural': 'alert'},
        ),
    ]
