# Generated by Django 2.1.5 on 2020-10-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0013_auto_20201003_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='alert',
            new_name='value',
        ),
    ]
