# Generated by Django 2.1.5 on 2020-10-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0014_auto_20201003_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='check',
            field=models.BooleanField(default=True),
        ),
    ]
