# Generated by Django 2.1.5 on 2020-10-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0017_remove_alert_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sold2',
            options={'ordering': ('tagid',), 'verbose_name_plural': 'sold2'},
        ),
    ]
