# Generated by Django 2.1.5 on 2020-10-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0019_auto_20201003_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sold1',
            options={'ordering': ('saleTime',), 'verbose_name_plural': 'sold1'},
        ),
        migrations.AlterModelOptions(
            name='sold2',
            options={'ordering': ('saleTime',), 'verbose_name_plural': 'sold2'},
        ),
    ]
