# Generated by Django 2.1.5 on 2021-03-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0020_auto_20201003_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='rfid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagid', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'rfid',
            },
        ),
    ]
